on: [push, pull_request, create, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: config/
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-v2-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Initialize workspace (west init)
        run: west init -l config
      - name: Update modules (west update)
        run: west update
      - name: Export zephyr CMake package (west zephyr-export)
        run: west zephyr-export
      - name: List modules (west list)
        run: west list
      - name: Build ComfyThumbs Left (west build)
        run: west build --pristine -s zmk/app -b comfythumbs_left -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: ComfyThumbs Left DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/comfythumbs_left.dts.pre.tmp
      - name: ComfyThumbs Left .config
        if: ${{ always() }}
        run: cat -n build/zephyr/.config
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 comfythumbs_left.uf2
      - name: Archive (ComfyThumbs Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: comfythumbs-left.uf2
      - name: Build ComfyThumbs Right (west build)
        run: west build --pristine -s zmk/app -b comfythumbs_right -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: ComfyThumbs Right DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/comfythumbs-right.dts.pre.tmp
      - name: ComfyThumbs Right .config
        if: ${{ always() }}
        run: cat -n build/zephyr/.config
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 comfythumbs_right.uf2
      - name: Archive (ComfyThumbs Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: comfythumbs_right.uf2
